runtime: java11
entrypoint: 'java -jar com.example.ktor-note-all.jar'
beta_settings:
  cloud_sql_instances: "true-server-427211-i9:us-central1:postgres"
env_variables:
  DATABASE_URL: "jdbc:postgresql://google/user_db?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=true-server-427211-i9:us-central1:postgres"
  JDBC_DRIVER: "org:postgresql:Driver"
  JWT_SECRET: "tushant"
  HASH_SECRET_KEY: "tushantHashKey"
  PORT: "8080"